apiVersion: devportal.kuadrant.io/v1alpha1
kind: APIKey
metadata:
  labels:
    app.kubernetes.io/name: developer-portal-controller
    app.kubernetes.io/managed-by: kustomize
  name: apikey-sample
spec:
  apiName: my-api-product
  apiNamespace: default
  planTier: premium
  useCase: "Integration with our mobile application for user authentication and data retrieval"
  requestedBy:
    userId: user-12345
    email: developer@example.com
  approvalMode: automatic
